package cn.oriki.mybatis.dao.mapper;

import cn.oriki.mybatis.domain.TCountry;
import java.util.List;

public interface TCountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country
     *
     * @mbggenerated
     */
    int insert(TCountry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country
     *
     * @mbggenerated
     */
    TCountry selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country
     *
     * @mbggenerated
     */
    List<TCountry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TCountry record);
}